version: "3"
services:
  mahout:
    image: mpolatcan/mahout:0.13.0-hadoop-3.3.0-java8
    container_name: mahout
    hostname: mahout
    environment:
      FS_DEFAULTFS: "hdfs://namenode:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "resourcemanager"

  resourcemanager:
    image: mpolatcan/hadoop:3.3.0-java8
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      HADOOP_DAEMONS: |
        resourcemanager
      FS_DEFAULTFS: "hdfs://namenode:9000"
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "1536"
    ports:
      - 8088:8088

  nodemanager:
    image: mpolatcan/hadoop:3.3.0-java8
    environment:
      HADOOP_DAEMONS: |
        nodemanager
      FS_DEFAULTFS: "hdfs://namenode:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "resourcemanager"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "1536"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
    ports:
      - 8042

  namenode:
    image: mpolatcan/hadoop:3.3.0-java8
    container_name: namenode
    hostname: namenode
    environment:
      HADOOP_DAEMONS: |
        namenode
      FS_DEFAULTFS: "hdfs://0.0.0.0:9000"
    ports:
      - 9870:9870

  secondarynamenode:
    image: mpolatcan/hadoop:3.3.0-java8
    container_name: secondarynamenode
    hostname: secondarynamenode
    environment:
      HADOOP_DAEMONS: |
        secondarynamenode
      FS_DEFAULTFS: "hdfs://namenode:9000"
    ports:
      - 9868:9868

  datanode:
    image: mpolatcan/hadoop:3.3.0-java8
    environment:
      HADOOP_DAEMONS: |
        datanode
      FS_DEFAULTFS: "hdfs://namenode:9000"
    ports:
      - 9864
