name: Mahout Docker Image Publish

on: [push]

jobs:
  build-mahout-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [mahout]
        java_version: [8]
        mahout_version: [0.13.0, 0.12.2, 0.11.2]
        hadoop_version: [3.2.1, 3.1.3, 2.9.2, 2.8.5, 2.7.7]
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.mahout_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
          --build-arg MAHOUT_VERSION=${{matrix.mahout_version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.mahout_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.mahout_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}